### ISSUE TITLE
部分材料无法处理

### ISSUE THREAD

**Issue by astatine-213** [penguin-statistics/ArkPlanner#38]
如题，运行后报错为：
Start to update data Tue Jan  2 19:32:34 2024.
Traceback (most recent call last):
  File "E:\python_code\游戏相关\明日方舟\ArkPlanner-1.1.1\main.py", line 22, in <module>
    mp.get_plan(required_dct, owned_dct, print_output='zh', outcome=True,
  File "E:\python_code\游戏相关\明日方舟\ArkPlanner-1.1.1\MaterialPlanning.py", line 479, in get_plan
    green = {item['name']: '%.3f' % (float(item['value'])/Price[self.item_id_to_name[self.item_name_to_id[output_lang][item['name']]]['zh']]) for item in values[2]['items']}
  File "E:\python_code\游戏相关\明日方舟\ArkPlanner-1.1.1\MaterialPlanning.py", line 479, in <dictcomp>
    green = {item['name']: '%.3f' % (float(item['value'])/Price[self.item_id_to_name[self.item_name_to_id[output_lang][item['name']]]['zh']]) for item in values[2]['items']}
KeyError: '环烃聚质'

初步猜测为新加入的几个材料没有对应的绿色材料（环烃聚质/晶体元件等）

其他信息：
owned.txt
双极纳米片 0
D32钢 5
聚合剂 4
RMA70-24 0
五水研磨石 3
三水锰矿 0
白马醇 1
改量装置 4
酮阵列 4
异铁块 16
聚酸酯块 0
糖聚块 0
提纯源岩 25
炽合金块 0
聚合凝胶 16
晶体电路 6
全新装置 135
酮凝集组 316
异铁组 33
聚酸酯组 243
糖组 97
固源岩组 374
凝胶 100
炽合金 198
RMA70-12 97
装置 313
酮凝集 581
异铁 605
聚酸酯 388
糖 416
固源岩 3729
双酮 244
异铁碎片 165
代糖 206
酯原料 267
破损装置 76
源岩 482

required.txt
聚合剂 33
双极纳米片 38
D32钢 31
晶体电子单元 39

**Comment by AlvISsReimu** [comment]
fixed in the latest version. Thx!
